# Generated by Django 4.2 on 2023-05-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0006_project_alter_membre_adresse_delete_commande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='logo',
            new_name='image',
        ),
    ]
