# Generated by Django 4.2 on 2023-05-15 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0007_rename_logo_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='logo',
        ),
    ]
